# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

demo_heure <- function() {
    invisible(.Call(`_confinement2_demo_heure`))
}

demo_lapin_1 <- function() {
    invisible(.Call(`_confinement2_demo_lapin_1`))
}

demo_lapin_2 <- function() {
    invisible(.Call(`_confinement2_demo_lapin_2`))
}

demo_rdv <- function() {
    invisible(.Call(`_confinement2_demo_rdv`))
}

rcpp_hello_world <- function() {
    .Call(`_confinement2_rcpp_hello_world`)
}

